# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13d70cd39e5dec68f30c05b74ea2c52b46231d214151e34761ece8d6596f537a22c1258074fba0e5dea3bac4880bb2593b8cbcfceec0cea1b8efff401eae9acd

test:
  secret_key_base: 610f874b1436702a7b3ca86283380a88d12d3ced868c5f81dbded8ad36c8dbdcfe608beb068371369d5b43ab65a3254407d346812630875dd389471353715aea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
